# Generated by Django 4.2.16 on 2024-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='is_attending',
            new_name='is_attending_wedding',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='party',
            name='category',
        ),
        migrations.RemoveField(
            model_name='party',
            name='is_attending',
        ),
        migrations.RemoveField(
            model_name='party',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='party',
            name='rehearsal_dinner',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
        migrations.AddField(
            model_name='guest',
            name='is_attending_brunch',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('guests', models.ManyToManyField(to='guests.guest', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('guests', models.ManyToManyField(to='guests.guest', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BringAlongMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('parties', models.ManyToManyField(to='guests.party', blank=True)),
                ('max_number', models.IntegerField()),
            ],
        ),
    ]
