# Generated by Django 4.2.16 on 2024-11-09 09:11

from django.db import migrations
from guests.models import DEFAULT_DIETS, DEFAULT_DRINKS


def fill_diets(apps, schema_editor):
    Diet = apps.get_model("guests", "Diet")
    for diet_option in DEFAULT_DIETS:
        diet = Diet(type=diet_option)
        diet.save()

def fill_drinks(apps, schema_editor):
    Drinks = apps.get_model("guests", "Drinks")
    for drinks_option in DEFAULT_DRINKS:
        drinks = Drinks(type=drinks_option)
        drinks.save()


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_my_model_changes'),
    ]

    operations = [
        migrations.RunPython(fill_diets),
        migrations.RunPython(fill_drinks),
    ]
