# Generated by Django 4.2.16 on 2024-11-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_alter_party_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
    ]
