# Generated by Django 4.2.16 on 2024-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_rename_first_name_guest_name_remove_guest_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_opened',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='invitation_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='save_the_date_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
