# Generated by Django 4.2.16 on 2024-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_alter_party_invitation_opened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_opened',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
