# Generated by Django 4.2.16 on 2024-11-09 11:12

from django.db import migrations
from guests.models import DEFAULT_DIETS, DEFAULT_DRINKS


def fill_drinks(apps, schema_editor):
    Drink = apps.get_model("guests", "Drink")
    for drink_option in DEFAULT_DRINKS:
        drink = Drink(type=drink_option)
        drink.save()


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_drink_remove_diet_guests_guest_diets_delete_drinks_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_drinks),
    ]
